"""Build a Korean research report from the inspected bibliography records."""
import json
import re
import hashlib
from pathlib import Path
from docx import Document
from docx.shared import Mm, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.opc.constants import RELATIONSHIP_TYPE as RT

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
OUT = ROOT / 'deliverables' / 'machining-literature-2026-09-20'
OUT.mkdir(parents=True, exist_ok=True)

def load(name):
    return json.loads((HERE/name).read_text(encoding='utf-8-sig'))

def text(value):
    if isinstance(value, list):
        return '; '.join(text(v) for v in value)
    return str(value) if value is not None else '발행연도 미표시'

inventory = load('current_citations.json')
records = sum([load(n+'.json') for n in ['foundations','standards','geometry','process']], [])
aliases = {'G08':'F01', 'P05':'G12'}
catalog = [r for r in records if r['id'] not in aliases]
by_id = {r['id']:r for r in records}
runtime_mapping = {
 'CNC_GEOMETRY':'P04', 'CNC_TOOL_DIMENSIONS':'P03',
 'CNC_FACE_RECOGNITION':'G02', 'CNC_ACCESS_SCOPE':'G12',
}

# Preserve the inventory wording. R12 has no verified full bibliographic record.
for r in inventory['original_literature']:
    if r['id'] == 'R12':
        r['title'] = 'Manufacturability of Parts with 3D-Annotated Model Generated by 3D-CAD'
        r['note'] = '한국어 편집본 5쪽. Mochizuki 표기는 기존 파일에 따름. 원문 연도·학술지·DOI와 그림은 미확인.'
    elif r['id'] in ['R08','R09','R10','R11']:
        r['title'] = {
          'R08':'KS D ISO ASTM 52902:2019',
          'R09':'KS D ISO ASTM 52903-1:2020',
          'R10':'KS D ISO ASTM 52903-2:2020',
          'R11':'KS D ISO/ASTM 52910:2018'
        }[r['id']]
        r['note'] = '기존 KS 캡처 자료. 누락·가림이 있어 완전한 표준 본문으로 취급하지 않음. ISO의 현재판과 KS 채택판은 별도 확인.'
    else:
        r['note'] = {
          'R01':'이번 절삭 조사에서 F02로 다시 연결. 적층과 절삭의 국소 난이도 및 설계 대안 참고.',
          'R02':'적층 부품 분해·LCA 연구. 현재 절삭 치수 검증의 직접 근거는 아님.',
          'R03':'FDM 설계·제작 전략 종설. 절삭 수치 기준으로 전용하지 않음.',
          'R04':'FDM 설계 고려사항. 공정별 조건과 원출처 확인 필요.',
          'R05':'재료 압출의 제조 제약. 본문과 표의 일부 수치 차이는 기존 기록에 보존.',
          'R06':'브리지·오버행의 실험 조건 근거. 현재 JIANG2018과 연결.',
          'R07':'B-rep 특징과 지식 기반 AM 검토. 현재 STAV2022와 연결.',
          'R13':'FDM 시험 자료. 본문·표의 성공 경계 불일치는 기존 기록에 보존.',
          'R14':'적층 제조성·조립성을 고려한 분해. 점수를 제조 성공 확률로 해석하지 않음.'
        }.get(r['id'],'기존 조사 기록을 재고 목록으로 연결. 이번 전체 원문 재독을 뜻하지 않음.')
    if r['id']=='R07':
        r['title']='Knowledge-based manufacturability assessment for optimization of additive manufacturing processes based on automated feature recognition from CAD models'

ACCESS = {
 'full_text_sections':'공개 원문 중 기재한 방법·결과 절 열람',
 'official_full_page':'공식 문서 본문 열람',
 'author_html_excerpt':'저자 공개 HTML 발췌 열람',
 'indexed_fulltext_excerpt_only':'검색 색인의 본문 발췌만 확인',
 'author_repository_readme':'저자 저장소 README 확인',
 'author_repository_readme_only':'저자 저장소 README 확인',
 'official_dataset_metadata':'공식 데이터 설명 확인',
 'dataset_metadata_only':'공식 데이터 설명 확인',
 'partial_pdf_pages':'누락 의심 PDF의 일부 쪽 확인',
}

doc = Document()
sec=doc.sections[0]
sec.page_width=Mm(210); sec.page_height=Mm(297)
sec.top_margin=Mm(19); sec.bottom_margin=Mm(18)
sec.left_margin=Mm(20); sec.right_margin=Mm(20)
sec.footer_distance=Mm(9)
for name in ['Normal','Title','Subtitle','Heading 1','Heading 2','Heading 3','Caption','List Bullet','List Number']:
    st=doc.styles[name]
    st.font.name='Malgun Gothic'
    st.font.color.rgb=RGBColor(0,0,0)
    st._element.get_or_add_rPr().rFonts.set(qn('w:eastAsia'),'맑은 고딕')
    st._element.get_or_add_rPr().rFonts.set(qn('w:ascii'),'Malgun Gothic')
    st.font.size=Pt(10.5)
    st.paragraph_format.space_after=Pt(5)
    st.paragraph_format.line_spacing=Pt(15)
    st.font.italic=False
    for border in st._element.xpath('.//w:pBdr'):
        border.getparent().remove(border)
    snap=OxmlElement('w:snapToGrid'); snap.set(qn('w:val'),'0'); st._element.get_or_add_pPr().append(snap)
doc.styles['Title'].font.size=Pt(25)
doc.styles['Title'].font.bold=True
doc.styles['Title'].paragraph_format.space_after=Pt(14)
doc.styles['Title'].paragraph_format.line_spacing=Pt(32)
doc.styles['Subtitle'].font.size=Pt(12)
doc.styles['Subtitle'].paragraph_format.line_spacing=Pt(17)
for name,size in [('Heading 1',16),('Heading 2',12.5),('Heading 3',11)]:
    st=doc.styles[name]; st.font.size=Pt(size); st.font.bold=True
    st.paragraph_format.space_before=Pt(12)
    st.paragraph_format.space_after=Pt(6)
    st.paragraph_format.keep_with_next=True
    st.paragraph_format.keep_together=True
    st.paragraph_format.line_spacing=Pt(size*1.4)
    for color in st._element.xpath('.//w:color'):
        for key in list(color.attrib):
            if key != qn('w:val'): del color.attrib[key]
        color.set(qn('w:val'),'000000')
doc.core_properties.title='절삭가공 제조성 검토 문헌 조사 보고서'
doc.core_properties.subject='현재 인용 자료와 추가 조사 문헌의 적용 범위 및 개발 우선순위'
doc.core_properties.author='DFM 프로젝트'
doc.core_properties.keywords='절삭가공, 제조성, DFM, STEP, 공차, 접근성, 문헌조사'
foot=sec.footer.paragraphs[0]; foot.alignment=WD_ALIGN_PARAGRAPH.CENTER
for val in ['PAGE']:
    fld=OxmlElement('w:fldSimple'); fld.set(qn('w:instr'),val)
    run=OxmlElement('w:r'); txt=OxmlElement('w:t'); txt.text='1'; run.append(txt); fld.append(run); foot._p.append(fld)

bookmark_id=0
def bookmark(p,name):
    global bookmark_id
    bookmark_id+=1
    a=OxmlElement('w:bookmarkStart'); a.set(qn('w:id'),str(bookmark_id)); a.set(qn('w:name'),name)
    b=OxmlElement('w:bookmarkEnd'); b.set(qn('w:id'),str(bookmark_id))
    p._p.insert(0,a); p._p.append(b)

def link(p,label,url=None,anchor=None):
    h=OxmlElement('w:hyperlink')
    if anchor: h.set(qn('w:anchor'),anchor)
    else: h.set(qn('r:id'),p.part.relate_to(url,RT.HYPERLINK,is_external=True))
    r=OxmlElement('w:r'); pr=OxmlElement('w:rPr')
    c=OxmlElement('w:color'); c.set(qn('w:val'),'185A7D'); pr.append(c)
    u=OxmlElement('w:u'); u.set(qn('w:val'),'single'); pr.append(u)
    r.append(pr); t=OxmlElement('w:t'); t.text=label; r.append(t); h.append(r); p._p.append(h)

def runs(p,s):
    # Inline links, bold, and literature IDs are all readable without tool tokens.
    pattern=r'(\[[^\]]+\]\(https?://[^\s]+?\)|\*\*.*?\*\*|\[(?:F|G|S|P)\d{2}\])'
    for token in re.split(pattern,s):
        if not token: continue
        match=re.fullmatch(r'\[([^\]]+)\]\((https?://.+)\)',token)
        if match: link(p,match[1],match[2])
        elif token.startswith('**'): p.add_run(token[2:-2]).bold=True
        elif re.fullmatch(r'\[(F|G|S|P)\d{2}\]',token):
            key=token[1:-1]; link(p,token,anchor='ref_'+aliases.get(key,key))
        else: p.add_run(token.replace('`',''))

def para(s,style=None):
    p=doc.add_paragraph(style=style); runs(p,s); return p

def labeled(label,value):
    p=doc.add_paragraph(); p.add_run(label+'  ').bold=True; runs(p,text(value)); return p

def table(rows,widths=None):
    t=doc.add_table(rows=0,cols=len(rows[0])); t.alignment=WD_TABLE_ALIGNMENT.CENTER; t.autofit=False
    widths=widths or [170/len(rows[0])]*len(rows[0])
    for col,w in zip(t.columns,widths): col.width=Mm(w)
    for i,row in enumerate(rows):
        cells=t.add_row().cells
        for j,(cell,value) in enumerate(zip(cells,row)):
            cell.width=Mm(widths[j]); cell.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
            cp=cell._tc.get_or_add_tcPr()
            sh=OxmlElement('w:shd'); sh.set(qn('w:fill'),'204D63' if i==0 else ('F3F6F8' if i%2==0 else 'FFFFFF')); cp.append(sh)
            mar=OxmlElement('w:tcMar')
            for side in ['top','left','bottom','right']:
                e=OxmlElement('w:'+side); e.set(qn('w:w'),'90'); e.set(qn('w:type'),'dxa'); mar.append(e)
            cp.append(mar)
            borders=OxmlElement('w:tcBorders')
            for side in ['top','left','bottom','right']:
                e=OxmlElement('w:'+side); e.set(qn('w:val'),'single'); e.set(qn('w:sz'),'4'); e.set(qn('w:color'),'D9D9D9'); borders.append(e)
            cp.append(borders)
            p=cell.paragraphs[0]; runs(p,str(value)); p.paragraph_format.space_after=Pt(1)
            p.paragraph_format.line_spacing=Pt(13)
            if i==0: p.paragraph_format.keep_with_next=True
            for run in p.runs:
                run.font.size=Pt(9)
                if i==0: run.bold=True; run.font.color.rgb=RGBColor(255,255,255)
            if len(str(value))<15: p.alignment=WD_ALIGN_PARAGRAPH.CENTER
        trpr=t.rows[-1]._tr.get_or_add_trPr()
        dont=OxmlElement('w:cantSplit'); trpr.append(dont)
        if i==0:
            repeat=OxmlElement('w:tblHeader'); trpr.append(repeat)
    doc.add_paragraph().paragraph_format.space_after=Pt(1)
    return t

def markdown(content):
    lines=content.splitlines(); i=0
    while i<len(lines):
        line=lines[i].strip()
        if not line: i+=1; continue
        if line.startswith('|'):
            rows=[]
            while i<len(lines) and lines[i].strip().startswith('|'):
                raw=lines[i].strip(); i+=1
                if re.fullmatch(r'[|:\-\s]+',raw): continue
                rows.append([v.strip() for v in raw.strip('|').split('|')])
            table(rows); continue
        match=re.match(r'^(#{1,4})\s+(.+)',line)
        if match:
            level=max(1,len(match[1])-1)
            heading=re.sub(r'^(\d+)\.\s+',r'\1 ',match[2].replace('**',''))
            p=doc.add_heading(heading,level=level)
            if level==1: bookmark(p,'sec_'+str(bookmark_id+1))
        elif line.startswith('- '): para(line[2:],'List Bullet')
        elif re.match(r'^\d+\.\s',line): para(re.sub(r'^\d+\.\s','',line),'List Number')
        else: para(line)
        i+=1

doc.add_paragraph('절삭가공 제조성 검토\n문헌 조사 보고서','Title')
doc.add_paragraph('현재 인용 자료와 추가 연구의 근거 및 개발 적용','Subtitle')
para('DFM 프로젝트  |  조사 기준일 2026년 9월 20일')
para('이 보고서는 현재 툴에 붙어 있는 출처를 확인하고, 절삭가공 검토를 확장하는 데 필요한 표준·논문·공구 및 CAM 문서를 연결합니다. 각 자료가 설명하는 문제, 필요한 입력, 허용되는 결론과 남은 한계를 함께 읽을 수 있도록 구성했습니다.')
para('현재 툴의 강점은 선택한 공구와 CAD 치수를 연결해 확인할 위치를 보여주는 것입니다. 다음 핵심 과제는 공구·홀더·소재·고정구를 포함한 접근성, 분할·교차 특징의 인식, 설계 공차의 입력입니다. 문헌에 제시된 방법의 존재와 우리 프로그램의 구현·검증 완료는 구분합니다.')
para('적층 관련 자료는 기존 인용 목록을 보존하는 범위로 정리합니다. 추가 심층 조사의 중심은 절삭이며, 사출·프레스는 대상에 포함하지 않습니다.')
doc.add_heading('읽는 순서',1)
for label,anchor in [('핵심 조사 결과와 개발 판단','main_start'),('현재 인용 자료 전체 목록','inventory_start'),('추가 조사와 재확인 문헌의 상세 카드','catalog_start'),('자료 확보와 수치 해석 시 주의사항','access_start')]:
    p=doc.add_paragraph(); link(p,label,anchor=anchor)
para('처음에는 본문의 결론과 개발 우선순위를 읽고, 필요한 기능의 문헌 ID를 눌러 상세 카드로 이동하세요. 카드는 서지·읽은 범위·기능 연결·필요 입력·해석 한계를 제공합니다. 원문 링크는 각 카드 끝에 있습니다.')
table([['목록','확인한 수','의미'],['현재 코드 출처','29개','적층·공통 입력 24개와 절삭 5개'],['최초 보유 문헌','14개','현재 코드 등록 목록과 일부 중복'],['심층 조사 카드',f'{len(catalog)}개','기존 절삭 자료 재확인과 신규 조사 포함; 표준 여러 부를 묶은 카드 포함']],[40,28,102])
para('위 숫자는 서로 더하는 총 논문 수가 아닙니다. 같은 자료가 코드·기존 문서·조사 카드에 다시 등장하면 대응 관계로 표시했습니다. 문헌 확보 수준은 카드별로 다릅니다.')
doc.add_page_break()
p=doc.add_heading('핵심 조사 결과',1); bookmark(p,'main_start')
body=(HERE/'report_body.md').read_text(encoding='utf-8-sig')
markdown(body.split('\n',1)[1] if body.startswith('# ') else body)

p=doc.add_heading('현재 인용 자료 전체 목록',1); bookmark(p,'inventory_start')
para('현재 코드의 SOURCES 등록부를 직접 추출했습니다. 등록됐다는 사실은 모든 분석 결과에 매번 인용된다는 뜻이 아닙니다. 각 검토 항목의 evidence 연결에 따라 사용됩니다. 아래 제목은 코드 등록명을 보존하며, 이번에 재확인한 절삭 자료의 정식 서지는 상세 카드에서 제공합니다.')
doc.add_heading('절삭 코드에 등록된 5개 출처',2)
for r in [r for r in inventory['runtime_registry'] if r['file'].startswith('dfm')]:
    block_start=len(doc.paragraphs)
    p=para(r['id']); p.runs[0].bold=True; p.paragraph_format.keep_with_next=True
    para(r['title'])
    target=runtime_mapping.get(r['id'])
    if target:
        para('이번 확인과 적용 한계는 ['+target+']에서 설명합니다.')
    else:
        para('이번 직접 열기는 시간 초과였습니다. 출처가 코드에 있다는 사실은 확인했지만 본문 재확인 완료로 처리하지 않습니다. 코너 비교는 실제 본문을 확인한 [P01]·[P04]와 기하 유도로 교차 검토합니다.')
    p=doc.add_paragraph(); link(p,'등록된 출처 열기',r['url'])
    para(f"등록 위치  {r['file']}  {r['line']}행")
    for bp in doc.paragraphs[block_start:-1]: bp.paragraph_format.keep_with_next=True
doc.add_heading('절삭 연구 문서에 추가된 5개 자료',2)
para('코드 5개와 기존 재감사 원문 9개를 합치면 서로 다른 출처는 10개입니다. 네 자료가 겹칩니다. 코드 밖의 추가 5개는 다음과 같습니다.')
table([['기존 번호','자료와 이번 카드','기존 역할'],['M01 E01','Sandvik 내부 코너 [P01]','공구 물림과 반경의 조건부 권고'],['M02 E02','Sandvik 홀과 포켓 [P02]','가공 전략과 칩 배출'],['M05 E06','Autodesk 드릴 충돌 [G13]','절삭 중 충돌과 연결 이동 분리'],['E07','Mirzendehdel 외 접근성 [G01]','유한 공구와 구성공간'],['E09','OCCT UVBounds [F07]','원통면 구간의 API 의미']],[30,73,67])

doc.add_heading('적층 및 공통 입력에 등록된 24개 출처',2)
para('여기는 현재 인용의 재고 목록입니다. 이번 작업에서 24개 원문을 모두 새로 읽거나 최신판을 전부 재검증한 목록은 아닙니다. 아래 확인 범위는 기존 등록 기록을 인용하며, 절삭 규칙의 직접 근거로 전용하지 않습니다.')
for r in [r for r in inventory['runtime_registry'] if r['file'].startswith('amdfm')]:
    block_start=len(doc.paragraphs)
    p=para(r['id']+'  '+r['title']); p.runs[0].bold=True; p.paragraph_format.keep_with_next=True
    labeled('사용 이유',r.get('use',''))
    labeled('기존 확인 범위',r.get('access','')+'; '+r.get('locator',''))
    if r.get('url'):
        p=doc.add_paragraph(); link(p,'등록된 원문 또는 공식 페이지',r['url'])
    else: para('온라인 주소 미등록. 저장소 LITERATURE.md R06과 원자료 색인에서 확인합니다.')
    for bp in doc.paragraphs[block_start:-1]: bp.paragraph_format.keep_with_next=True

doc.add_heading('최초 보유 문헌 14개의 연결 관계',2)
para('R 번호는 기존 LITERATURE.md의 식별자를 유지합니다. 일부 자료는 현재 등록된 출처와 겹치고, 일부는 개발 배경 자료입니다. 과거 연구 노트의 읽기 기록과 이번 조사 범위를 혼동하지 않도록 별도 목록으로 남깁니다.')
for r in inventory['original_literature']:
    block_start=len(doc.paragraphs)
    p=para(r['id']+'  '+r['title']); p.runs[0].bold=True; p.paragraph_format.keep_with_next=True
    para(r['name']+'. '+r['note'])
    if r.get('doi'):
        p=doc.add_paragraph(); link(p,'DOI '+r['doi'],'https://doi.org/'+r['doi'])
    for bp in doc.paragraphs[block_start:-1]: bp.paragraph_format.keep_with_next=True

doc.add_page_break()
p=doc.add_heading('조사 문헌 상세 카드',1); bookmark(p,'catalog_start')
para('F는 기초 평가·검증 자료, S는 표준·제품정의·계측, G는 기하·특징 인식·공정 계획, P는 공구·공정·물리 자료입니다. P0는 현재 근거와 해석을 정비하는 우선순위, P1은 다음 기능 개발, P2는 추가 입력과 검증을 확보한 뒤 수행할 연구입니다. 이는 이 프로젝트의 개발 판단이며 문헌이 지정한 일정이 아닙니다.')
para('중복 자료는 G08을 F01에, P05를 G12에 통합했습니다. 기존 코드의 CNC_CORNER는 직접 본문 재확인 실패 상태로 앞 목록에 보존했습니다. 표준 카드 S07은 2부, S10은 3부를 묶었으므로 카드 수와 표준 개수가 같지 않습니다.')
for prefix,name in [('F','평가의 정의와 입력 검증'),('S','표준과 제품 요구사항'),('G','형상 인식과 접근성 및 공정 계획'),('P','공구와 가공 조건 및 물리 검증')]:
    doc.add_heading(name,2)
    for r in [r for r in catalog if r['id'].startswith(prefix)]:
        p=doc.add_heading(r['id']+' 문헌 정보',3); bookmark(p,'ref_'+r['id'])
        p=para(r['title']); p.runs[0].bold=True; p.paragraph_format.keep_with_next=True
        p=para(text(r['authors'])+' | '+text(r.get('year'))+' | '+text(r['kind'])); p.paragraph_format.keep_with_next=True
        labeled('읽은 범위',ACCESS.get(text(r['access_level']),text(r['access_level']))+'. '+text(r['reviewed_sections']))
        labeled('핵심 내용',r['findings'])
        labeled('툴에 필요한 이유',r['supports'])
        labeled('필요한 입력',r['inputs'])
        labeled('확대해서 해석하면 안 되는 내용',r['does_not_support'])
        labeled('개발 우선순위',r['implementation_priority'])
        labeled('판본과 확인 사항',r['status_notes'])
        p=doc.add_paragraph(); link(p,'공식 출처 또는 저자 원문',r['url'])
        if r.get('fulltext_url') and r['fulltext_url']!=r['url']:
            p.add_run('  |  '); link(p,'열람 원문',r['fulltext_url'])
        if r.get('doi'):
            p.add_run('  |  '); link(p,'DOI '+r['doi'],'https://doi.org/'+r['doi'])
        p.add_run('  |  확인 '+r['checked_date'])

doc.add_page_break()
p=doc.add_heading('자료 확보와 수치 해석 시 주의사항',1); bookmark(p,'access_start')
para('이 조사는 현재 구현의 질문에서 출발한 목적 중심의 문헌 조사입니다. 학술 데이터베이스 전체를 동일 검색식으로 전수 선별한 체계적 문헌고찰이나 메타분석은 아닙니다. 최신 연구와 전통 연구를 함께 검토하되, 논문에 인용된 참고문헌까지 전부 읽은 것으로 처리하지 않았습니다.')
para('검색 범위에는 자동 제조성 평가, B-rep 특징 인식, 공구 접근성, 구성공간, 제거 체적, 셋업과 고정구, 절삭력과 얇은 벽, 채터, 가공시간, STEP PMI, ISO GPS와 ASME 제품정의가 포함됩니다. 2026년 9월 20일에 공식 표준 카탈로그·출판사·저자 공개 원고·정부기관·공구 및 CAM 공급사 자료를 확인했습니다. 사출·프레스 및 절삭 전 공정의 완전한 문헌망라를 주장하지 않습니다.')
table([['확보 수준','허용되는 사용'],['원문 관련 절 열람','읽은 정의·가정·수식·실험 범위 안에서 해석'],['공식 표준 카탈로그','제목·판·현행 상태·적용 범위 확인; 유료 조항 구현 근거는 아님'],['초록이나 검색 색인','자료 선정과 연구 방향 참고; 상세 식과 성능 확정 금지'],['코드 등록부만 확인','현재 프로그램에 무엇이 인용됐는지의 재고 기록']],[46,124])
para('직접 열기 실패와 부분 자료는 카드에서 표시했습니다. 특히 Hubs 코너 페이지, Hierarchical CADNet의 직접 원문, 일부 절삭역학 원저의 유료 본문, MRSEV PDF의 누락 의심 부분을 완전히 확보한 자료로 처리하지 않습니다. 원문 판본이 다르면 PDF 물리 페이지와 출판 쪽수를 구분해야 합니다.')
para('표준을 실제 판정 규칙으로 구현할 때에는 필요한 부분의 정식 본문, 적용 판, 단위와 조항, 수정사항을 먼저 확보해야 합니다. 기존 도면에 지정된 판을 현재판으로 자동 교체해서는 안 됩니다. 제조사의 수치 권고는 해당 공구·소재·작업 방법·서비스 조건과 함께 저장해야 합니다.')
para('문헌 읽기는 소프트웨어 정확도 시험, 실제 CAM 실행, 실물 제작·측정을 대신하지 않습니다. 이번 산출물은 문헌과 개발 판단을 정리한 문서이며, 애플리케이션 기능이나 가공 성공 확률 모델을 새로 구현한 결과가 아닙니다.')

outpath=OUT/'절삭가공_제조성검토_문헌조사_2026-09-20.docx'
doc.save(outpath)
(HERE/'catalog.json').write_text(json.dumps(dict(date='2026-09-20',record_count=len(catalog),aliases=aliases,records=catalog),ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
# Editable text companion keeps every card, including full links.
md=['# 절삭가공 제조성 검토 문헌 조사 보고서','조사일 2026-09-20', (HERE/'report_body.md').read_text(encoding='utf-8-sig'),'## 조사 문헌 상세 카드']
for r in catalog:
    md.extend(['### '+r['id']+' '+r['title'], text(r['authors'])+' / '+text(r.get('year')),
       '확인: '+text(r['access_level'])+' / '+text(r['reviewed_sections']),
       '핵심: '+text(r['findings']),'적용: '+text(r['supports']), '입력: '+text(r['inputs']),
       '한계: '+text(r['does_not_support']), '판본: '+text(r['status_notes']), '[원문]('+r['url']+')'])
(HERE/'REPORT.md').write_text('\n\n'.join(md)+'\n',encoding='utf-8')
manifest=dict(output=str(outpath),sha256=hashlib.sha256(outpath.read_bytes()).hexdigest(),bibliography_cards=len(catalog),registered_sources=29,legacy_records=14,aliases=aliases)
(HERE/'build_manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps(manifest,ensure_ascii=False))
