"""Read-only citation inventory, separate from source verification."""
import ast
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = Path(__file__).resolve().parent

def evaluate(node):
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == 'dict':
        return {kw.arg: evaluate(kw.value) for kw in node.keywords}
    if isinstance(node, ast.Dict):
        return {evaluate(k): evaluate(v) for k, v in zip(node.keys, node.values)}
    return ast.literal_eval(node)

records = []
for rel, category in [('amdfm/evidence.py', '현재 적층 및 공통 입력 출처 등록'), ('dfm/machining.py', '현재 절삭 출처 등록')]:
    raw = (ROOT / rel).read_bytes()
    tree = ast.parse(raw.decode('utf-8-sig'))
    node = next(n for n in tree.body if isinstance(n, ast.Assign) and any(isinstance(t, ast.Name) and t.id == 'SOURCES' for t in n.targets))
    sources = evaluate(node.value)
    for key, value_node in zip(node.value.keys, node.value.values):
        key = evaluate(key)
        records.append(dict(id=key, registry=category, file=rel, line=value_node.lineno,
            file_sha256=hashlib.sha256(raw).hexdigest(), **sources[key]))

text = (ROOT / 'docs/project-knowledge/LITERATURE.md').read_text(encoding='utf-8-sig')
legacy = []
for match in re.finditer(r'^## (R\d+) — ([^\n]+)\n(.*?)(?=^## |\Z)', text, re.M|re.S):
    key, name, content = match.groups()
    title = re.search(r'\*\*(.+?)\*\*', content)
    doi = re.search(r'DOI:\s*([^\s(]+)', content)
    extracted_title=title.group(1) if title else name
    display_title=name if key in ['R08','R09','R10'] else extracted_title
    if key=='R12': display_title='Manufacturability of Parts with 3D-Annotated Model Generated by 3D-CAD (정식 원문 서지 미확인)'
    legacy.append(dict(id=key, name=name, title=display_title, raw_first_bold_text=extracted_title,
        doi=doi.group(1).rstrip('.') if doi else None, existing_note=content.strip(),
        review_status='기존 2026-09-10~11 조사 기록의 재고 목록; 이번 전체 원문 재독을 뜻하지 않음'))

# Historical URL occurrences are useful for traceability, not a count of papers.
url_rows = []
for path in sorted((ROOT/'docs').rglob('*.md')):
    if OUT in path.parents:
        continue
    for lineno, line in enumerate(path.read_text(encoding='utf-8-sig').splitlines(), 1):
        for url in re.findall(r'https?://[^\s<>\]\)]+', line):
            url_rows.append(dict(file=path.relative_to(ROOT).as_posix(), line=lineno, url=url.rstrip('.,;')))

data = dict(checked_date='2026-09-20', scope='Registry inventory is not full-text verification; documentation occurrences include historical and technical links.',
    runtime_registry_count=len(records), runtime_registry=records, original_literature=legacy,
    documentation_url_occurrences=url_rows)
(OUT/'current_citations.json').write_text(json.dumps(data, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
print(json.dumps(dict(registry=len(records), am=sum(r['file'].startswith('amdfm') for r in records), cnc=sum(r['file'].startswith('dfm') for r in records), original=len(legacy), documentation_url_occurrences=len(url_rows)), ensure_ascii=False))
