[theme]
base = "light"
primaryColor = "#315f78"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f4f6"
textColor = "#24313a"
font = "sans serif"

[server]
maxUploadSize = 80
address = "127.0.0.1"

[browser]
gatherUsageStats = false

